### ISSUE TITLE
Idea: Listener class & use Dynaconf

### ISSUE THREAD

**Issue by mraniki** [AlberLC/multibot#2]
Hi,
I'm very interested by your approach. Not sure if you have look at [Dynaconf](https://www.dynaconf.com) for settings like token, web hook and co.
I'm have started to use it to simplify my bot code and I'm looking something like yours for multibot support ([my tool](https://github.com/mraniki/tt) so I have the following parameters that I can reuse across discord, telegram and matrix initiated bot for the same code:
```
host = "0.0.0.0"
port = 8080

bot_prefix = "/"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_restart = "restart"
bot_command_quote = "q"


bot_token = ""
bot_channel_id = ""

telethon_api_id = ''
telethon_api_hash = ''

matrix_hostname = ""
matrix_user = ""
matrix_pass = ""

discord_webhook_id = ""
discord_webhook_token = ""
```
Ideally I searching for a common listener  as I use apprise to send data back to the user.

something like 
`import multibot`

`bot = multibot(DISCORD_BOT_TOKEN) ` or     
`bot =  multibot (api_id=['TELEGRAM_API_ID'], api_hash=['TELEGRAM_API_HASH'], bot_token=['TELEGRAM_BOT_TOKEN'], channel_id)`

**Comment by AlberLC** [comment]
I don't quite understand what you need. Do you have a problem with the configuration files or creating two bots that run at the same time (discord and telegram)?

First of all, I have to warn you that multibot does not work with prefixes, the bots created with this infrastructure focus on reading messages and replying. Of course you can make it ignore messages that don't start with "/" but, for example, in Discord the commands will not appear in a "pretty" and autocompleted way because those so-called "slash commands" are not really configured.

In this part of my [readme](https://github.com/AlberLC/multibot#run-multiple-bots) I give an example code to run 3 bots, one for each supported platform (discord, telegram and twitch).

I know that my guide is not very explanatory but it boils down to creating 2 bots, in your case, that need to listen to the same type of message. Each bot has to register a function or callback where the message will be processed.

For convenience in the example that I have given you, I use inheritance and mixins to create a single method and register it for both bots.

![image](https://user-images.githubusercontent.com/37489786/236649136-855ffd24-b5e1-4f67-8639-b4e0f4356e52.png)

Here in the [readme](https://github.com/AlberLC/multibot#ways-to-design-your-bot) it is explained through examples how the [register](https://github.com/AlberLC/multibot/blob/1df1b05e60b60c71f5b852f30ea6f1ac2a25cc07/multibot/bots/multi_bot.py#L872) method behaves by which you tell multibot when to execute said callback.

**Example:**
If you want to process messages that contain something similar to "bitcoin" in their text.
```python
class MyBot(DiscordBot):
    def __init__(self):
        super().__init__(os.environ['DISCORD_BOT_TOKEN'])

    def _add_handlers(self):
        super()._add_handlers()
        self.register(self.function_name_1, 'bitcoin')

    async def function_name_1(self, message: Message):
        ...
```

You can set the hardness of the filter with the `min_score` parameter. If you want exactly the user to put "bitcoin" without any misspelling, it would be `self.register(self.function_name_1, 'bitcoin', min_score=1)`.

If you want to use prefixes you can always put the prefix directly `self.register(self.function_name_1, '/bitcoin', min_score=1)` or if you want to process all messages starting with `/` you can do this:
```python
class MyBot(DiscordBot):
    def __init__(self):
        super().__init__(os.environ['DISCORD_BOT_TOKEN'])

    def _add_handlers(self):
        super()._add_handlers()
        self.register(self.function_name_1, always=True)

    async def function_name_1(self, message: Message):
        if not message.text.startswith('/'):
            return
        ...
```

Hope this can help you.

**Comment by mraniki** [comment]
Thanks for the reply. Let me dig up more the readme. 👍
